version: '3'
services:
    app:
        build: .
        env_file: .env
        ports:
          - '8080:80'
        volumes:
          - storage:/var/www/storage
          - .env:/var/www/.env
        restart: unless-stopped
    mariadb:
        image: 'mariadb:10'
        environment:
          MARIADB_DATABASE: ${DB_DATABASE}
          MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
          MARIADB_PASSWORD: ${DB_PASSWORD}
          MARIADB_USER: ${DB_USERNAME}
        volumes:
          - db:/var/lib/mysql
        restart: unless-stopped
volumes:
  db:
  storage:
